# Generated by Django 4.0.3 on 2022-04-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Alojamiento',
        ),
    ]
